---
permalink: audit/arct-archive-retrieve-from-cloud-tier.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, ARCT, Archive Retrieve from Cloud-Tier 
summary: Este mensaje se genera cuando se recuperan datos de objetos archivados de un sistema de almacenamiento de archivado externo, que se conecta a la StorageGRID a través de la API de S3. 
---
= ARCT: Recuperación de archivos a partir de nivel de cloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este mensaje se genera cuando se recuperan datos de objetos archivados de un sistema de almacenamiento de archivado externo, que se conecta a la StorageGRID a través de la API de S3.

[cols="1a,1a,4a"]
|===
| Codificación | Campo | Descripción 


 a| 
CBID
 a| 
ID del bloque de contenido
 a| 
Identificador único del bloque de contenido recuperado.



 a| 
CSIZ
 a| 
Tamaño de contenido
 a| 
El tamaño del objeto en bytes. El valor sólo es preciso para las recuperar correctamente.



 a| 
TRANSFORMACIÓN DIGITAL
 a| 
Código de resultado
 a| 
Devuelve correcto (SUCS) o el error notificado por el backend.



 a| 
SUID
 a| 
Identificador único de almacenamiento
 a| 
Identificador único (UUID) del sistema de almacenamiento de archivado externo.



 a| 
TIEMPO
 a| 
Tiempo
 a| 
Tiempo de procesamiento total de la solicitud en microsegundos.

|===