---
permalink: audit/audit-messages-and-object-lifecycle.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, log, object lifecycle, ingest, retrieve, delete, s3, swift, timing, ILM, Information lifecycle management, archive node, archive nodes 
summary: 'Se generan mensajes de auditoría cada vez que se procesa, recupera o elimina un objeto. Puede identificar estas transacciones en el registro de auditoría localizando mensajes de auditoría específicos de la API \(S3 o Swift\).' 
---
= ¿Cuándo se generan los mensajes de auditoría?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se generan mensajes de auditoría cada vez que se procesa, recupera o elimina un objeto. Puede identificar estas transacciones en el registro de auditoría localizando mensajes de auditoría específicos de la API (S3 o Swift).

Los mensajes de auditoría se vinculan a través de identificadores específicos de cada protocolo.

[cols="1a,1a"]
|===
| Protocolo | Codificación 


 a| 
Vinculación de operaciones de S3
 a| 
S3BK (cuchara), S3KY (llave) o ambos



 a| 
Vinculación de operaciones de Swift
 a| 
WCON (contenedor), WOBJ (objeto) o ambos



 a| 
Vinculación de las operaciones internas
 a| 
CBID (identificador interno del objeto)

|===


== Plazos de los mensajes de auditoría

Debido a factores como las diferencias de tiempo entre nodos de cuadrícula, tamaño de objeto y retrasos de red, el orden de los mensajes de auditoría generados por los diferentes servicios puede variar con respecto al que se muestra en los ejemplos de esta sección.



== Nodos de archivado

La serie de mensajes de auditoría generados cuando un nodo de archivado envía datos de objeto a un sistema de almacenamiento de archivado externo es similar a la de los nodos de almacenamiento, excepto que no hay ningún mensaje SCMT (confirmación de objeto de almacén), Y los mensajes ATCE (Archive Object Store Begin) y ASCE (Archive Object Store End) se generan para cada copia archivada de datos de objeto.

La serie de mensajes de auditoría generados cuando un nodo de archivado recupera datos de objeto de un sistema de almacenamiento de archivado externo es similar a la de los nodos de almacenamiento, excepto que los mensajes ARCB (Archive Object Retrieve Begin) y ARCE (Archive Object Retrieve End) se generan para cada copia recuperada de los datos de objeto.

La serie de mensajes de auditoría generados cuando un nodo de archivado elimina los datos de objeto de un sistema de almacenamiento de archivado externo es similar a la de los nodos de almacenamiento, excepto que no hay ningún mensaje SREM (Object Store Remove) y hay un mensaje AREM (Archive Object Remove) para cada solicitud de eliminación.
