---
permalink: audit/object-storage-audit-messages.html 
sidebar: sidebar 
keywords: audit, object storage, object management, object retrieval, node transfer, verification, APCT, ARCB, ARCE, ARCT, AREM, ASCE, ASCT, ATCE, AVCC, BROR, CBSE, CBRE, CGRR, EBDL, EBKR, SCMT, SREM 
summary: Debería estar familiarizado con los mensajes de auditoría que pertenecen a la categoría de auditoría de almacenamiento de objetos. Estos son eventos relacionados con el almacenamiento y la gestión de objetos dentro del sistema StorageGRID. Entre estas se incluyen las recuperaciones y almacenamiento de objetos, el nodo de grid a transferencias de Grid-nodo y las verificaciones. 
---
= Mensajes de auditoría del almacenamiento de objetos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los mensajes de auditoría que pertenecen a la categoría de auditoría del almacenamiento de objetos se utilizan para eventos relacionados con el almacenamiento y la gestión de los objetos dentro del sistema StorageGRID. Entre estas se incluyen las recuperaciones y almacenamiento de objetos, el nodo de grid a transferencias de Grid-nodo y las verificaciones.

[cols="1a,2a,1a"]
|===
| Codificación | Descripción | Consulte 


 a| 
APCT
 a| 
Análisis de archivo desde Cloud-Tier: Los datos de objetos archivados se eliminan de un sistema de almacenamiento de archivado externo, que se conecta a StorageGRID a través de la API S3.
 a| 
link:apct-archive-purge-from-cloud-tier.html["APCT: Purga de archivos desde la capa de cloud"]



 a| 
ARCB
 a| 
Inicio de recuperación de objetos de archivo: El servicio ARC inicia la recuperación de datos de objetos desde el sistema de almacenamiento de archivos externo.
 a| 
link:arcb-archive-object-retrieve-begin.html["ARCB: Inicio de recuperación de objetos de archivo"]



 a| 
ARCE
 a| 
Fin de recuperación de objeto de archivo: Los datos de objeto se han recuperado de un sistema de almacenamiento de archivos externo y el servicio ARC informa del estado de la operación de recuperación.
 a| 
link:arce-archive-object-retrieve-end.html["ARCE: Fin de recuperación de objetos archivados"]



 a| 
ARCT
 a| 
Recuperación de archivo desde Cloud-Tier: Los datos de objetos archivados se recuperan de un sistema de almacenamiento de archivado externo, que se conecta a StorageGRID a través de la API S3.
 a| 
link:arct-archive-retrieve-from-cloud-tier.html["ARCT: Recuperación de archivos a partir de nivel de cloud"]



 a| 
AREM
 a| 
Eliminación de objetos de archivo: Un bloque de contenido se ha eliminado correctamente o sin éxito del sistema de almacenamiento de archivos externo.
 a| 
link:arem-archive-object-remove.html["AREM: Eliminación de objeto de archivado"]



 a| 
ASCE
 a| 
Fin del almacén de objetos archivados: Se ha escrito un bloque de contenido en el sistema de almacenamiento de archivos externo y el servicio ARC informa del estado de la operación de escritura.
 a| 
link:asce-archive-object-store-end.html["ASCE: Fin del almacén de objetos de archivo"]



 a| 
ASCT
 a| 
Almacenamiento de archivos Cloud-Tier: Los datos de objetos se almacenan en un sistema de almacenamiento de archivado externo, que se conecta a la StorageGRID a través de la API de S3.
 a| 
link:asct-archive-store-cloud-tier.html["ASCT: Archive Store Cloud-Tier"]



 a| 
ATCE
 a| 
Inicio del almacén de objetos de archivado: Se ha iniciado la escritura de un bloque de contenido en un almacenamiento de archivado externo.
 a| 
link:atce-archive-object-store-begin.html["ATCE: Inicio del almacén de objetos de archivado"]



 a| 
AVCC
 a| 
Validación de archivo Configuración de nivel de cloud: La configuración de la cuenta y el bloque proporcionados se validó correctamente o sin éxito.
 a| 
link:avcc-archive-validate-cloud-tier-configuration.html["AVCC: Validación de archivo de la configuración de Cloud-Tier"]



 a| 
BROR
 a| 
Solicitud de solo lectura de bloque: Un bloque entró o salió del modo de solo lectura.
 a| 
link:bror-bucket-read-only-request.html["BROR: Solicitud de solo lectura de bucket"]



 a| 
CBSE
 a| 
Objeto Send End: La entidad de origen completó una operación de transferencia de datos de un nodo de cuadrícula a un nodo de cuadrícula.
 a| 
link:cbse-object-send-end.html["CBSE: Fin de envío de objeto"]



 a| 
CBRE
 a| 
Fin de recepción de objetos: La entidad de destino completó una operación de transferencia de datos de Grid-node hacia Grid-node.
 a| 
link:cbre-object-receive-end.html["CBRE: Fin de recepción de objeto"]



 a| 
CGRR
 a| 
Solicitud de replicación entre grid: StorageGRID intentó realizar una operación de replicación entre grid para replicar objetos entre buckets de una conexión de federación de grid.
 a| 
link:cgrr-cross-grid-replication-request.html["CGRR: Solicitud de Replicación de Cuadrícula Cruzada"]



 a| 
EBDL
 a| 
Empty Bucket Delete: El análisis de ILM eliminó un objeto de un bloque que está eliminando todos los objetos (realizando una operación de bloque vacía).
 a| 
link:ebdl-empty-bucket-delete.html["EBDL: Eliminación de bloque vacío"]



 a| 
EBKR
 a| 
Solicitud de depósito vacío: Un usuario ha enviado una solicitud para activar o desactivar el depósito vacío (es decir, para eliminar objetos de depósito o para dejar de suprimir objetos).
 a| 
link:ebkr-empty-bucket-request.html["EBKR: Solicitud de depósito vacío"]



 a| 
SCMT
 a| 
Confirmación del almacén de objetos: Un bloque de contenido se almacenó y verificó completamente, y ahora se puede solicitar.
 a| 
link:scmt-object-store-commit.html["SCMT: Solicitud de confirmación del almacén de objetos"]



 a| 
SREM
 a| 
Almacén de objetos Quitar: Se ha eliminado un bloque de contenido de un nodo de cuadrícula y ya no se puede solicitar directamente.
 a| 
link:srem-object-store-remove.html["SREM: Almacén de objetos Quitar"]

|===