---
permalink: upgrade/removed-or-deprecated-features.html 
sidebar: sidebar 
keywords:  
summary: Algunas funciones y funcionalidades se eliminaron o quedaron obsoletas en esta versión. Revise estos elementos para saber si necesita actualizar las aplicaciones del cliente o modificar la configuración antes de realizar la actualización. 
---
= Características y capacidades eliminadas o obsoletas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Algunas funciones y funcionalidades se eliminaron o quedaron obsoletas en esta versión. Revise estos elementos para saber si necesita actualizar las aplicaciones del cliente o modificar la configuración antes de realizar la actualización.



== Definiciones

Anticuado:: La característica *no debe ser usada en nuevos ambientes de producción. Los entornos de producción existentes pueden seguir utilizando la función.
Fin de la vida:: Última versión enviada que contiene la función. Ninguna versión futura admitirá la función.
Quitada:: Primera versión que *no* contiene la característica.




== Compatibilidad con fin de la función StorageGRID 11,8

Las funciones obsoletas se eliminarán en las versiones principales N+2. Por ejemplo, si una característica está obsoleta en la versión N (por ejemplo, 6,3), la última versión en la que existirá la característica es N+1 (por ejemplo, 6,4). La versión N+2 (por ejemplo, 6,5) es la primera versión cuando la función no existe en el producto.

Consulte https://mysupport.netapp.com/site/info/version-support["Soporte de la versión del software"^] para obtener más información.


NOTE: En ciertas situaciones, NetApp podría terminar el soporte para determinadas funciones antes de lo indicado.

[cols="3a,1a,1a,1a"]
|===
| Función | Anticuado | Fin de la vida | Quitada 


 a| 
Soporte para nodos de archivado
 a| 
11,7
 a| 
11,8
 a| 
11,9



 a| 
Auditar la exportación a través de CIFS/Samba
 a| 
11,1
 a| 
11,6
 a| 
11,7



 a| 
Servicio CLB
 a| 
11,4
 a| 
11,6
 a| 
11,7



 a| 
Tiempo de ejecución del contenedor Docker
 a| 
11,8
 a| 
11,9
 a| 
12,0



 a| 
Exportación de auditoría NFS
 a| 
11,8
 a| 
11,9
 a| 
12,0



 a| 
Soporte para API Swift
 a| 
11,7
 a| 
11,9
 a| 
12,0

|===