---
permalink: ubuntu/configuring-host-storage.html 
sidebar: sidebar 
keywords: how to configure host storage 
summary: Se deben asignar los volúmenes de almacenamiento en bloque a cada host. 
---
= Configurar el almacenamiento del host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se deben asignar los volúmenes de almacenamiento en bloque a cada host.

.Antes de empezar
Ha revisado los siguientes temas, que le proporcionan información necesaria para realizar esta tarea:

link:storage-and-performance-requirements.html["Los requisitos de almacenamiento y rendimiento"]

link:node-container-migration-requirements.html["Requisitos de migración de contenedores de nodos"]

.Acerca de esta tarea
Cuando asigne volúmenes de almacenamiento de bloques (LUN) a hosts, utilice las tablas en «Requisitos de almacenamiento» para determinar lo siguiente:

* Número de volúmenes necesarios para cada host (según la cantidad y los tipos de nodos que se pondrán en marcha en ese host)
* Categoría de almacenamiento para cada volumen (es decir, datos del sistema o datos de objetos)
* El tamaño de cada volumen


Utilizará esta información, así como el nombre persistente asignado por Linux a cada volumen físico cuando implemente nodos StorageGRID en el host.


NOTE: No es necesario crear particiones, formatear o montar ninguno de estos volúmenes; solo debe asegurarse de que sean visibles para los hosts.


NOTE: Solo se requiere un LUN de datos de objetos para los nodos de almacenamiento solo de metadatos.

Evite utilizar archivos especiales de dispositivos raw (`/dev/sdb`, por ejemplo) al redactar la lista de nombres de volumen. Estos archivos pueden cambiar entre reinicios del host, lo que impacta en el funcionamiento correcto del sistema. Si utiliza LUN iSCSI y rutas múltiples de asignación de dispositivos, considere el uso de alias multivía en la `/dev/mapper` directorio, especialmente si la topología SAN incluye rutas de red redundantes al almacenamiento compartido. De forma alternativa, puede utilizar los enlaces programables creados por el sistema en `/dev/disk/by-path/` para los nombres de dispositivos persistentes.

Por ejemplo:

[listing]
----
ls -l
$ ls -l /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:00:07.1-ata-2 -> ../../sr0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:1:0 -> ../../sdb
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:2:0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:3:0 -> ../../sdd
----
Los resultados serán distintos para cada instalación.

Asigne nombres descriptivos a cada uno de estos volúmenes de almacenamiento en bloques para simplificar la instalación inicial de StorageGRID y los procedimientos de mantenimiento futuros. Si se utiliza el controlador multivía del asignador de dispositivos para acceder de forma redundante a volúmenes de almacenamiento compartido, es posible utilizar el `alias` en su `/etc/multipath.conf` archivo.

Por ejemplo:

[listing]
----
multipaths {
     multipath {
          wwid 3600a09800059d6df00005df2573c2c30
          alias docker-storage-volume-hostA
     }
     multipath {
          wwid 3600a09800059d6df00005df3573c2c30
          alias sgws-adm1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df4573c2c30
          alias sgws-adm1-audit-logs
     }
     multipath {
          wwid 3600a09800059d6df00005df5573c2c30
          alias sgws-adm1-tables
     }
     multipath {
          wwid 3600a09800059d6df00005df6573c2c30
          alias sgws-gw1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-rangedb-0
     }
     …
----
Esto hará que los alias aparezcan como dispositivos de bloque en el `/dev/mapper` directorio en el host, lo que permite especificar un nombre descriptivo y de fácil validación cada vez que una operación de configuración o mantenimiento requiere especificar un volumen de almacenamiento de bloques.


NOTE: Si está configurando almacenamiento compartido para admitir la migración de nodos de StorageGRID y el uso de rutas múltiples de asignación de dispositivos, puede crear e instalar un común `/etc/multipath.conf` en todos los hosts ubicados conjuntamente. Solo hay que asegurarse de usar un volumen de almacenamiento de Docker diferente en cada host. El uso de alias e incluir el nombre de host de destino en el alias de cada LUN de volumen de almacenamiento de Docker facilitará su recordatorio y le recomienda que lo haga.

.Información relacionada
link:storage-and-performance-requirements.html["Los requisitos de almacenamiento y rendimiento"]

link:node-container-migration-requirements.html["Requisitos de migración de contenedores de nodos"]
