---
permalink: ubuntu/installing-linux.html 
sidebar: sidebar 
keywords: how to install Linux 
summary: Debe instalar StorageGRID en todos los hosts de grid de Ubuntu o Debian. Para ver una lista de las versiones admitidas, use la herramienta de matriz de interoperabilidad de NetApp. 
---
= Instale Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe instalar StorageGRID en todos los hosts de grid de Ubuntu o Debian. Para ver una lista de las versiones admitidas, use la herramienta de matriz de interoperabilidad de NetApp.


NOTE: Asegúrese de que su sistema operativo esté actualizado al kernel 4,15 de Linux o superior.

.Pasos
. Instalar Linux en todos los hosts de grid físicos o virtuales de acuerdo con las instrucciones del mayorista o del procedimiento estándar.
+

NOTE: No instale ningún entorno de escritorio gráfico. Al instalar Ubuntu, debe seleccionar *utilidades estándar del sistema*. Se recomienda seleccionar *OpenSSH Server* para habilitar el acceso ssh a sus hosts Ubuntu. Todas las demás opciones pueden permanecer desactivadas.

. Asegúrese de que todos los hosts tengan acceso a los repositorios de paquetes de Ubuntu o Debian.
. Si el intercambio está activado:
+
.. Ejecute el siguiente comando: `$ sudo swapoff --all`
.. Eliminar todas las entradas de intercambio de `/etc/fstab` para mantener los ajustes.
+

NOTE: Si no se deshabilita por completo el intercambio, el rendimiento se puede reducir considerablemente.




