---
permalink: tenant/configuring-cross-origin-resource-sharing-cors.html 
sidebar: sidebar 
keywords: how to configure cross-origin resource sharing, cors 
summary: 'Puede configurar el uso compartido de recursos de origen cruzado \(CORS\) para un depósito de S3 si desea que las aplicaciones web de otros dominios puedan acceder a ese depósito y a los objetos de ese depósito.' 
---
= Configurar el uso compartido de recursos de origen cruzado (CORS)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar el uso compartido de recursos de origen cruzado (CORS) para un depósito de S3 si desea que las aplicaciones web de otros dominios puedan acceder a ese depósito y a los objetos de ese depósito.

.Antes de empezar
* Ha iniciado sesión en el administrador de inquilinos mediante un link:../admin/web-browser-requirements.html["navegador web compatible"].
* Pertenece a un grupo de usuarios que tiene el link:tenant-management-permissions.html["Gestione todos los bloques o permisos de acceso raíz"]. Estos permisos anulan la configuración de los permisos en las políticas de grupo o bloque.


.Acerca de esta tarea
El uso compartido de recursos de origen cruzado (CORS) es un mecanismo de seguridad que permite a las aplicaciones web de cliente de un dominio acceder a los recursos de un dominio diferente. Por ejemplo, supongamos que se utiliza un bloque de S3 llamado `Images` para almacenar gráficos. Configurando CORS para `Images` bloque, puede permitir que las imágenes de ese bloque se muestren en el sitio web `+http://www.example.com+`.



== Activar CORS para un cucharón

.Pasos
. Utilice un editor de texto para crear el XML necesario.
+
Este ejemplo muestra el XML utilizado para habilitar CORS para un bloque de S3. Este XML permite a cualquier dominio enviar solicitudes GET al bloque, pero sólo permite el `+http://www.example.com+` Dominio para enviar solicitudes DE PUBLICACIÓN Y ELIMINACIÓN. Se permiten todos los encabezados de las solicitudes.

+
[listing]
----
<CORSConfiguration
    xmlns="http://s3.amazonaws.com/doc/2020-10-22/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>http://www.example.com</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
----
+
Para obtener más información acerca del XML de configuración de CORS, consulte http://docs.aws.amazon.com/AmazonS3/latest/dev/Welcome.html["Documentación de Amazon Web Services (AWS): Guía para desarrolladores de Amazon simple Storage Service"^].

. Seleccione *Ver cubos* en el panel de control o seleccione *ALMACENAMIENTO (S3)* > *Buckets*.
. Seleccione el nombre del cubo de la tabla.
+
Aparece la página de detalles bucket.

. En la pestaña *Acceso a cubos*, selecciona el acordeón *Uso compartido de recursos de origen cruzado (CORS)*.
. Seleccione la casilla de verificación *Activar CORS*.
. Pegue el XML de configuración de CORS en el cuadro de texto.
. Seleccione *Guardar cambios*.




== Modificar el ajuste de CORS

.Pasos
. Actualice el XML de configuración de CORS en el cuadro de texto, o seleccione *Borrar* para empezar de nuevo.
. Seleccione *Guardar cambios*.




== Desactive el ajuste CORS

.Pasos
. Desactive la casilla de verificación *Activar CORS*.
. Seleccione *Guardar cambios*.

