---
permalink: admin/archiving-to-cloud-through-s3-api.html 
sidebar: sidebar 
keywords: archive node to AWS, Amazon Web Services 
summary: 'Puede configurar un nodo de archivado para conectarse directamente a Amazon Web Services \(AWS\) o a cualquier otro sistema que pueda conectarse desde el sistema StorageGRID a través de la API S3.' 
---
= Archivado en el cloud mediante la API de S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar un nodo de archivado para conectarse directamente a Amazon Web Services (AWS) o a cualquier otro sistema que pueda conectarse al sistema StorageGRID a través de la API de S3.

[CAUTION]
====
La compatibilidad con los nodos de archivo está obsoleta y se eliminará en una versión futura. El traslado de objetos de un nodo de archivado a un sistema de almacenamiento de archivado externo a través de la API de S3 ha sido sustituido por los pools de almacenamiento en cloud de ILM, que ofrecen más funcionalidades.

La opción Cloud Tiering - Simple Storage Service (S3) también queda obsoleta. Si está utilizando un nodo de archivado con esta opción, link:../admin/migrating-objects-from-cloud-tiering-s3-to-cloud-storage-pool.html["Migre sus objetos a un pool de almacenamiento en la nube"] en su lugar.

Además, debe eliminar los nodos de archivado de la política de gestión de la vida útil de la información activa en StorageGRID 11,7 o versiones anteriores. La eliminación de datos de objetos almacenados en nodos de archivado simplificará las actualizaciones futuras. Consulte link:../ilm/working-with-ilm-rules-and-ilm-policies.html["Trabajar con reglas de ILM y políticas de ILM"].

====