---
permalink: s3/head-object.html 
sidebar: sidebar 
keywords: HeadObject 
summary: Puede utilizar la solicitud S3 HeadObject para recuperar metadatos de un objeto sin devolver el objeto en sí. 
---
= Objeto principal
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar la solicitud S3 HeadObject para recuperar metadatos de un objeto sin devolver el objeto en sí. Si el objeto está almacenado en un Cloud Storage Pool, puede usar HeadObject para determinar el estado de transición del objeto.



== HeadObject y objetos multiparte

Puede utilizar el `partNumber` parámetro de solicitud para recuperar metadatos de una parte específica de un objeto de varias partes o segmentado.  La `x-amz-mp-parts-count` el elemento de respuesta indica cuántas partes tiene el objeto.

Puede ajustar `partNumber` a 1 para objetos segmentados/multiparte y objetos no segmentados/no multiparte; sin embargo, el `x-amz-mp-parts-count` el elemento de respuesta sólo se devuelve para objetos segmentados o multipartes.



== Caracteres UTF-8 en los metadatos de usuario

StorageGRID no analiza ni interpreta caracteres UTF-8 escapados en los metadatos definidos por el usuario. Las solicitudes de CABECERA para un objeto con caracteres UTF-8 que se han escapado en los metadatos definidos por el usuario no devuelven el `x-amz-missing-meta` encabezado si el nombre o valor de clave incluye caracteres no imprimibles.



== Encabezado de solicitud no compatible

El siguiente encabezado de solicitud no es compatible y devuelve `XNotImplemented`:

* `x-amz-website-redirect-location`




== Creación de versiones

Si es un `versionId` no se especifica el subrecurso, la operación busca la versión más reciente del objeto en un bloque con versiones. Si la versión actual del objeto es un marcador de borrado, se devuelve un estado de no encontrado con el `x-amz-delete-marker` encabezado de respuesta establecido en `true`.



== Solicitar encabezados para el cifrado del servidor con claves de cifrado proporcionadas por el cliente (SSE-C)

Utilice los tres encabezados si el objeto está cifrado con una clave única que ha proporcionado.

* `x-amz-server-side-encryption-customer-algorithm`: Especificar `AES256`.
* `x-amz-server-side-encryption-customer-key`: Especifique la clave de cifrado del objeto.
* `x-amz-server-side-encryption-customer-key-MD5`: Especifique el resumen MD5 de la clave de cifrado del objeto.



CAUTION: Las claves de cifrado que proporcione no se almacenan nunca. Si pierde una clave de cifrado, perderá el objeto correspondiente. Antes de utilizar las claves proporcionadas por el cliente para proteger los datos de objetos, revise las consideraciones que se deben tener en link:using-server-side-encryption.html["Usar cifrado del servidor"].



== Respuestas HeadObject para objetos de Cloud Storage Pool

Si el objeto se almacena en un link:../ilm/what-cloud-storage-pool-is.html["Pool de almacenamiento en cloud"], se devuelven las siguientes cabeceras de respuesta:

* `x-amz-storage-class: GLACIER`
* `x-amz-restore`


Los encabezados de respuesta proporcionan información sobre el estado de un objeto a medida que se mueve a un pool de almacenamiento en cloud, y que, opcionalmente, se realiza la transición a un estado no recuperable y se restaura.

[cols="1a,1a"]
|===
| Estado del objeto | Respuesta a HeadObject 


 a| 
Objeto ingerido en StorageGRID pero aún no evaluado por ILM, u objeto almacenado en un pool de almacenamiento tradicional o utilizando código de borrado
 a| 
`200 OK` (No se devuelve ningún encabezado de respuesta especial).



 a| 
Objeto en el pool de almacenamiento en cloud pero todavía no ha realizado la transición a un estado no recuperable
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: Ongoing-request=“false”, expire-date=“sáb, 23 de julio de 20 2030 00:00:00 GMT”

Hasta que el objeto se realice la transición a un estado no recuperable, el valor de `expiry-date` se configura a una hora distante en el futuro. El sistema StorageGRID no controla la hora exacta de la transición.



 a| 
El objeto ha pasado a estar en estado no recuperable, pero también existe al menos una copia en la cuadrícula
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: Ongoing-request=“false”, expire-date=“sáb, 23 de julio de 20 2030 00:00:00 GMT”

Valor para `expiry-date` se configura a una hora distante en el futuro.

*Nota*: Si la copia en la cuadrícula no está disponible (por ejemplo, un nodo de almacenamiento está caído), debe emitir un link:post-object-restore.html["RestoreObject"] Solicite restaurar la copia del Cloud Storage Pool antes de poder recuperar el objeto correctamente.



 a| 
El objeto ha pasado a un estado que no se puede recuperar y no existe ninguna copia en la cuadrícula
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`



 a| 
Objeto en proceso de restauración a partir de un estado no recuperable
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

'x-amz-restore: ongoing-request= 'true'



 a| 
Objeto completamente restaurado en el pool de almacenamiento en cloud
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: Ongoing-request=“false”, expire-date=“sáb, 23 de julio de 20 2018 00:00:00 GMT”

La `expiry-date` Indica si el objeto del Cloud Storage Pool regresará a un estado no recuperable.

|===


=== Objetos de varias partes o segmentos en el pool de almacenamiento en cloud

Si cargó un objeto con varias partes o StorageGRID dividió un objeto grande en segmentos, StorageGRID determina si el objeto está disponible en el pool de almacenamiento en cloud al muestrear un subconjunto de las partes o segmentos del objeto. En algunos casos, una solicitud HeadObject podría devolver incorrectamente `x-amz-restore: Ongoing-request=“false” cuando algunas partes del objeto ya han sido transitadas a un estado no recuperable o cuando algunas partes del objeto aún no han sido restauradas.



== HeadObject y replicación entre grid

Si está utilizando link:../admin/grid-federation-overview.html["federación de grid"] y.. link:../tenant/grid-federation-manage-cross-grid-replication.html["replicación entre grid"] Está habilitado para un depósito, el cliente S3 puede verificar el estado de replicación de un objeto emitiendo una solicitud HeadObject. La respuesta incluye los recursos específicos de StorageGRID `x-ntap-sg-cgr-replication-status` cabecera de respuesta, que tendrá uno de los siguientes valores:

[cols="1a,2a"]
|===
| Cuadrícula | Estado de replicación 


 a| 
Origen
 a| 
* *ÉXITO*: La replicación fue exitosa.
* *PENDIENTE*: El objeto aún no ha sido replicado.
* *FALLO*: La replicación falló con un fallo permanente. Un usuario debe resolver el error.




 a| 
Destino
 a| 
*REPLICA*: El objeto fue replicado desde la cuadrícula de origen.

|===

NOTE: StorageGRID no admite el `x-amz-replication-status` encabezado.
