---
permalink: maintain/recovering-from-primary-admin-node-failures.html 
sidebar: sidebar 
keywords: storagegrid, recover, primary admin node failure 
summary: 'Debe completar un conjunto específico de tareas para recuperar el sistema después de un fallo en un nodo de administrador principal. El nodo de administración principal aloja el servicio nodo de administración de configuración \(CMN\) de la cuadrícula.' 
---
= Recuperación de fallos de nodo de administración principal: Descripción general
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe completar un conjunto específico de tareas para recuperar el sistema después de un fallo en un nodo de administrador principal. El nodo de administrador principal aloja el servicio Configuration Management Node (CMN) de la cuadrícula.

Un nodo de administrador principal con fallos se debe reemplazar inmediatamente. El servicio nodo de gestión de configuración (CMN) del nodo de administración principal es responsable de emitir bloques de identificadores de objetos para la cuadrícula. Estos identificadores se asignan a los objetos a medida que se ingieren. No se pueden ingerir nuevos objetos a menos que haya identificadores disponibles. La ingesta de objetos puede continuar mientras el CMN no está disponible porque el suministro de identificadores de aproximadamente un mes se almacena en caché en la cuadrícula. Sin embargo, después de que se agoten los identificadores almacenados en caché, no es posible añadir objetos nuevos.


CAUTION: Debe reparar o sustituir un nodo de administrador principal con fallos dentro de un mes aproximadamente, o bien el grid podría perder su capacidad de procesar objetos nuevos. El período de tiempo exacto depende de la tasa de ingesta de objetos: Si necesita una evaluación más precisa del plazo para el grid, póngase en contacto con el soporte técnico.
