---
permalink: maintain/replacing-archive-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, archive node 
summary: Para recuperar un nodo de archivado, primero debe reemplazar el nodo. 
---
= Reemplace el nodo de archivado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para recuperar un nodo de archivado, primero debe reemplazar el nodo.

Debe seleccionar el procedimiento de sustitución de nodo para su plataforma. Los pasos para reemplazar un nodo son los mismos para todos los tipos de nodos de grid.

[cols="1a,2a"]
|===
| Plataforma | Procedimiento 


 a| 
VMware
 a| 
link:all-node-types-replacing-vmware-node.html["Sustituya un nodo VMware"]



 a| 
Linux
 a| 
link:all-node-types-replacing-linux-node.html["Sustituya un nodo Linux"]



 a| 
OpenStack
 a| 
Las operaciones de recuperación ya no son compatibles con los archivos de disco de máquinas virtuales y los scripts de OpenStack que proporciona NetApp. Si necesita recuperar un nodo que se ejecuta en una implementación de OpenStack, descargue los archivos para el sistema operativo Linux. A continuación, siga el procedimiento para link:all-node-types-replacing-linux-node.html["Reemplazar un nodo Linux"].

|===