---
permalink: maintain/restarting-server-manager-and-all-services.html 
sidebar: sidebar 
keywords: storagegrid, recover, server manager, restart server manager 
summary: Es posible que deba reiniciar el administrador de servidores y todos los servicios que se ejecuten en un nodo de grid. 
---
= Reinicie Server Manager y todos los servicios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que deba reiniciar el administrador de servidores y todos los servicios que se ejecuten en un nodo de grid.

.Antes de empezar
Usted tiene la `Passwords.txt` archivo.

.Pasos
. Inicie sesión en el nodo de grid:
+
.. Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a la raíz: `su -`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.


+
Cuando ha iniciado sesión como root, el símbolo del sistema cambia de `$` para `#`.

. Reinicie Server Manager y todos los servicios del nodo de grid: `service servermanager restart`
+
El Administrador del servidor y todos los servicios del nodo de grid se detienen y, a continuación, se reinician.

+

NOTE: Con el `restart` el comando es el mismo que utiliza el `stop` comando seguido de `start` comando.

. Cierre la sesión del shell de comandos: `exit`

