---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: Puede apagar un nodo de cuadrícula desde el shell de comandos del nodo. 
---
= Apague el nodo de grid
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede apagar un nodo de grid desde el shell de comandos del nodo.

.Antes de empezar
* Usted tiene la `Passwords.txt` archivo.


.Acerca de esta tarea
Antes de realizar este procedimiento, revise estas consideraciones:

* En general, no debe apagar más de un nodo a la vez para evitar interrupciones.
* No apague un nodo durante un procedimiento de mantenimiento a menos que la documentación o el soporte técnico lo indiquen explícitamente.
* El proceso de apagado se basa en la ubicación en la que se instala el nodo, de la siguiente manera:
+
** Apagar un nodo de VMware apaga la máquina virtual.
** Apagar un nodo Linux apaga el contenedor.
** Apagar un nodo de un dispositivo StorageGRID apaga la controladora de computación.


* Si tiene previsto apagar más de un nodo de almacenamiento en un sitio, detenga la incorporación de objetos en el sitio durante una hora aproximadamente antes de apagar los nodos.
+
Si alguna regla de ILM utiliza la opción de ingesta *Dual commit* (o si una regla usa la opción *Balanced* y no se pueden crear inmediatamente todas las copias requeridas), StorageGRID confirma inmediatamente cualquier objeto recién ingerido en dos nodos de almacenamiento en el mismo sitio y evalúa ILM más tarde. Si se apaga más de un nodo de almacenamiento en un sitio, es posible que no pueda acceder a los objetos recién procesados durante la interrupción del apagado. También es posible que se produzca un error en las operaciones de escritura si hay demasiados nodos de almacenamiento disponibles en el sitio. Consulte link:../ilm/index.html["Gestión de objetos con ILM"].



.Pasos
. Inicie sesión en el nodo de grid:
+
.. Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a la raíz: `su -`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.


+
Cuando ha iniciado sesión como root, el símbolo del sistema cambia de `$` para `#`.

. Detenga todos los servicios: `service servermanager stop`
+
Los servicios pueden tardar hasta 15 minutos en apagarse, y es posible que desee iniciar sesión en el sistema de forma remota para supervisar el proceso de apagado.

. Si el nodo se está ejecutando en una máquina virtual de VMware o si es un nodo del dispositivo, utilice el comando shutdown: `shutdown -h now`
+
Realice este paso independientemente del resultado del `service servermanager stop` comando.

+

NOTE: Después de emitir el `shutdown -h now` debe apagar y encender el dispositivo para reiniciar el nodo.

+
Para el dispositivo, este comando apaga la controladora pero el dispositivo sigue encendido. Debe completar el siguiente paso.

. Si va a apagar un nodo del dispositivo, siga los pasos del dispositivo.
+
[role="tabbed-block"]
====
.SGF6112
--
.. Apague el aparato.
.. Espere a que se apague el LED de alimentación azul.


--
.SG6000
--
.. Espere a que se apague el LED verde de caché activa en la parte posterior de las controladoras de almacenamiento.
+
Este LED está encendido cuando es necesario escribir en las unidades los datos en caché. Debe esperar a que este LED se apague antes de apagarse.

.. Apague el aparato y espere a que se apague el LED de alimentación azul.


--
.SG5700
--
.. Espere a que se apague el LED verde de caché activa en la parte posterior de la controladora de almacenamiento.
+
Este LED está encendido cuando es necesario escribir en las unidades los datos en caché. Debe esperar a que este LED se apague antes de apagarse.

.. Apague el aparato y espere a que todos los LED y la actividad de visualización de siete segmentos se detengan.


--
.SG100 o SG1000
--
.. Apague el aparato.
.. Espere a que se apague el LED de alimentación azul.


--
====

