---
permalink: maintain/starting-or-restarting-service.html 
sidebar: sidebar 
keywords: storagegrid, recover, service, start service, restart service 
summary: Es posible que deba iniciar un servicio detenido o que deba detener y reiniciar un servicio. 
---
= Inicie o reinicie el servicio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que deba iniciar un servicio detenido o que deba detener y reiniciar un servicio.

.Antes de empezar
Usted tiene la `Passwords.txt` archivo.

.Pasos
. Inicie sesión en el nodo de grid:
+
.. Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a la raíz: `su -`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.


+
Cuando ha iniciado sesión como root, el símbolo del sistema cambia de `$` para `#`.

. Decida qué comando emitir, en función de si el servicio se está ejecutando actualmente o detenido.
+
** Si el servicio está detenido actualmente, utilice `start` comando para iniciar el servicio manualmente: `service _servicename_ start`
+
Por ejemplo:

+
[listing]
----
service ldr start
----
** Si el servicio se está ejecutando actualmente, utilice `restart` comando para detener el servicio y, a continuación, reiniciarlo: `service _servicename_ restart`
+
Por ejemplo:

+
[listing]
----
service ldr restart
----
+

NOTE: Con el `restart` el comando es el mismo que utiliza el `stop` comando seguido de `start` comando. Puede emitir `restart` incluso si el servicio se detiene actualmente.



. Cierre la sesión del shell de comandos: `exit`

