---
permalink: maintain/viewing-current-status-of-service.html 
sidebar: sidebar 
keywords: storagegrid, recover, service, status 
summary: Puede ver el estado actual de los servicios que se ejecutan en un nodo de grid en cualquier momento. 
---
= Ver el estado actual del servicio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ver el estado actual de los servicios que se ejecutan en un nodo de grid en cualquier momento.

.Antes de empezar
Usted tiene la `Passwords.txt` archivo.

.Pasos
. Inicie sesión en el nodo de grid:
+
.. Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a la raíz: `su -`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.


+
Cuando ha iniciado sesión como root, el símbolo del sistema cambia de `$` para `#`.

. Ver el estado actual de un servicio que se ejecuta en un nodo de cuadrícula: `*service _servicename_ status*
Se informa del estado actual del servicio solicitado que se ejecuta en el nodo de cuadrícula (en ejecución o no). Por ejemplo:
+
[listing]
----
cmn running for 1d, 14h, 21m, 2s
----
. Cierre la sesión del shell de comandos: `*exit*`

