---
permalink: maintain/warnings-and-considerations-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, warning 
summary: Si un nodo de grid falla, debe recuperarlo Lo antes posible.. Antes de empezar, debe revisar todas las advertencias y consideraciones de la recuperación de nodos. 
---
= Advertencias y consideraciones sobre los procesos de recuperación de nodos de grid
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si un nodo de grid falla, debe recuperarlo Lo antes posible.. Antes de empezar, debe revisar todas las advertencias y consideraciones de la recuperación de nodos.


CAUTION: StorageGRID es un sistema distribuido compuesto por varios nodos que funcionan entre sí. No utilice instantáneas de disco para restaurar nodos de grid. En su lugar, consulte los procedimientos de recuperación y mantenimiento de cada tipo de nodo.

Entre los motivos para recuperar un Lo antes posible. de nodo de Grid con errores se incluyen los siguientes:

* Un nodo de grid fallido puede reducir la redundancia de los datos del sistema y del objeto, lo que le deja vulnerable al riesgo de pérdida permanente de datos si falla otro nodo.
* Un nodo de grid fallido puede afectar la eficiencia de las operaciones diarias de‐a‐.
* Un nodo de grid con errores puede reducir su capacidad para supervisar las operaciones del sistema.
* Un nodo de grid fallido puede provocar un error interno de 500 servidores si se aplican reglas estrictas de ILM.
* Si un nodo de grid no se recupera con la rapidez, es posible que aumenten los tiempos de recuperación. Por ejemplo, se podrían desarrollar colas que se deben borrar antes de que se complete la recuperación.


Siga siempre el procedimiento de recuperación para el tipo específico de nodo de cuadrícula que se va a recuperar. Los procedimientos de recuperación varían en función de los nodos de administración principales o no primarios, los nodos de puerta de enlace, los nodos de archivado, los nodos de dispositivos y los nodos de almacenamiento.



== Condiciones previas para la recuperación de nodos de grid

Al recuperar nodos de grid, se da por sentado las siguientes condiciones:

* Se reemplazó y configuró el hardware físico o virtual que falló.
* La versión del instalador de dispositivos StorageGRID del dispositivo de sustitución coincide con la versión de software de su sistema StorageGRID, como se describe en https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html["Comprobar y actualizar la versión de StorageGRID Appliance Installer"^].
* Si recupera un nodo de grid que no es el nodo de administrador principal, hay conectividad entre el nodo de grid que se está recuperando y el nodo de administrador principal.




== El orden de recuperación de nodos si se produce un error en un servidor que aloja más de un nodo de grid

Si falla un servidor que aloja más de un nodo de grid, puede recuperar los nodos en cualquier orden. Sin embargo, si el servidor con el fallo aloja el nodo de administración principal, primero debe recuperar dicho nodo. Si se recupera el nodo de administrador principal, primero se impide que las recuperaciones de otros nodos se detenguen a medida que esperan para ponerse en contacto con el nodo de administración principal.



== Direcciones IP para nodos recuperados

No intente recuperar un nodo usando una dirección IP que esté actualmente asignada a cualquier otro nodo. Cuando se implementa el nodo nuevo, use la dirección IP actual del nodo con errores o una dirección IP sin usar.

Si utiliza una dirección IP nueva para implementar el nodo nuevo y después recuperar el nodo, la dirección IP nueva se seguirá usando para el nodo recuperado. Si desea revertir a la dirección IP original, utilice la herramienta Change IP una vez completada la recuperación.
