---
permalink: primer/what-archive-node-is.html 
sidebar: sidebar 
keywords: archive node 
summary: La compatibilidad con los nodos de archivo está obsoleta y se eliminará en una versión futura. 
---
= ¿Qué es un nodo de archivado?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La compatibilidad con los nodos de archivo está obsoleta y se eliminará en una versión futura.

[CAUTION]
====
La compatibilidad con los nodos de archivo está obsoleta y se eliminará en una versión futura. El traslado de objetos de un nodo de archivado a un sistema de almacenamiento de archivado externo a través de la API de S3 ha sido sustituido por los pools de almacenamiento en cloud de ILM, que ofrecen más funcionalidades.

La opción Cloud Tiering - Simple Storage Service (S3) también queda obsoleta. Si está utilizando un nodo de archivado con esta opción, link:../admin/migrating-objects-from-cloud-tiering-s3-to-cloud-storage-pool.html["Migre sus objetos a un pool de almacenamiento en la nube"] en su lugar.

Además, debe eliminar los nodos de archivado de las políticas de ILM activas en StorageGRID 11,7 o versiones anteriores. La eliminación de datos de objetos almacenados en nodos de archivado simplificará las actualizaciones futuras. Consulte link:../ilm/working-with-ilm-rules-and-ilm-policies.html["Trabajar con reglas de ILM y políticas de ILM"].

====


== Servicios principales para nodos de archivado

La siguiente tabla muestra los servicios principales para los nodos de archivado; sin embargo, esta tabla no enumera todos los servicios de nodo.

[cols="1a,2a"]
|===
| Servicio | Función de la tecla 


 a| 
Archivo (ARC)
 a| 
Se comunica con un sistema de almacenamiento en cinta externo Tivoli Storage Manager (TSM).



 a| 
Monitor de estado del servidor (SSM)
 a| 
Supervisa el sistema operativo y el hardware subyacente.

|===