---
permalink: expand/copying-audit-logs.html 
sidebar: sidebar 
keywords: copy audit log, Admin Node expansion, 
summary: Cuando agrega un nuevo nodo de administración a través de un procedimiento de expansión, su servicio AMS solo registra eventos y acciones que se producen después de que se une al sistema. Según sea necesario, se pueden copiar registros de auditoría de un nodo de administrador instalado previamente en el nuevo nodo de administrador de ampliación de modo que este se encuentre sincronizado con el resto del sistema de StorageGRID. 
---
= Copiar registros de auditoría
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando agrega un nuevo nodo de administración a través de un procedimiento de expansión, su servicio AMS solo registra eventos y acciones que se producen después de que se une al sistema. Según sea necesario, se pueden copiar registros de auditoría de un nodo de administrador instalado previamente en el nuevo nodo de administrador de ampliación de modo que este se encuentre sincronizado con el resto del sistema de StorageGRID.

.Antes de empezar
* Completó los pasos de ampliación necesarios para añadir un nodo de administrador.
* Usted tiene la `Passwords.txt` archivo.


.Acerca de esta tarea
Para que los mensajes de auditoría históricos estén disponibles en un nodo de administración nuevo, debe copiar los archivos de registro de auditoría manualmente desde un nodo de administración existente al nodo de administración de expansión.

[NOTE]
====
De manera predeterminada, se envía la información de auditoría al registro de auditoría en los nodos admin. Puede omitir estos pasos si se aplica alguna de las siguientes situaciones:

* Se configuraron un servidor de syslog externo y registros de auditoría ahora se envían al servidor de syslog en lugar de a los nodos de administrador.
* Ha especificado explícitamente que los mensajes de auditoría se deben guardar sólo en los nodos locales que los han generado.


Consulte link:../monitor/configure-audit-messages.html["Configurar los mensajes de auditoría y los destinos de registro"] para obtener más detalles.

====
.Pasos
. Inicie sesión en el nodo de administración principal:
+
.. Introduzca el siguiente comando: `ssh _admin@_primary_Admin_Node_IP_`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a la raíz: `su -`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.
+
Cuando ha iniciado sesión como root, el símbolo del sistema cambia de `$` para `#`.



. Detenga el servicio AMS para evitar que cree un nuevo archivo: `service ams stop`
. Navegue al directorio de exportación de auditoría:
+
`cd /var/local/log`

. Cambie el nombre del origen `audit.log` Archivo para asegurarse de que no sobrescribe el archivo en el nodo de administración de expansión al que está copiando:
+
[listing]
----
ls -l
mv audit.log _new_name_.txt
----
. Copie todos los archivos de registro de auditoría en la ubicación de destino en el nodo de administración de expansión:
+
`scp -p * _IP_address_:/var/local/log`

. Si se le solicita la frase de acceso para `/root/.ssh/id_rsa`, Escriba la contraseña de acceso SSH para el nodo de administración principal que se muestra en `Passwords.txt` archivo.
. Restaure el original `audit.log` archivo:
+
`mv _new_name_.txt audit.log`

. Inicie el servicio AMS:
+
`service ams start`

. Cierre la sesión en el servidor:
+
`exit`

. Inicie sesión en el nodo de administrador de ampliación:
+
.. Introduzca el siguiente comando: `ssh admin@_expansion_Admin_Node_IP_`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a la raíz: `su -`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.
+
Cuando ha iniciado sesión como root, el símbolo del sistema cambia de `$` para `#`.



. Actualice la configuración del usuario y del grupo para los archivos de registro de auditoría:
+
`cd /var/local/log`

+
`chown ams-user:bycast *`

. Cierre la sesión en el servidor:
+
`exit`


