---
permalink: troubleshoot/searching-for-and-restoring-potentially-lost-objects.html 
sidebar: sidebar 
keywords: how to search lost object, how to restore lost object, how to find lost object 
summary: 'Puede ser posible encontrar y restaurar objetos que han activado una alarma objetos perdidos (PERDIDOS) y una alerta *objeto perdido* y que se ha identificado como potencialmente perdido.' 
---
= Busque y restaure objetos que se han perdido potencialmente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ser posible encontrar y restaurar objetos que han activado una alarma objetos perdidos (PERDIDOS) y una alerta *objeto perdido* y que se ha identificado como potencialmente perdido.

.Antes de empezar
* Tiene el UUID de cualquier objeto perdido, como se identifica en link:../troubleshoot/investigating-lost-objects.html["Investigar los objetos perdidos"].
* Usted tiene la `Passwords.txt` archivo.


.Acerca de esta tarea
Puede seguir este procedimiento para buscar copias replicadas del objeto perdido en otra parte de la cuadrícula. En la mayoría de los casos, el objeto perdido no se encuentra. Sin embargo, en algunos casos, es posible que pueda encontrar y restaurar un objeto replicado perdido si realiza una acción rápida.


CAUTION: Póngase en contacto con el soporte técnico para obtener ayuda con este procedimiento.

.Pasos
. En un nodo de administrador, busque los registros de auditoría para las posibles ubicaciones de objetos:
+
.. Inicie sesión en el nodo de grid:
+
... Introduzca el siguiente comando: `ssh admin@grid_node_IP`
... Introduzca la contraseña que aparece en `Passwords.txt` archivo.
... Introduzca el siguiente comando para cambiar a la raíz: `su -`
... Introduzca la contraseña que aparece en `Passwords.txt` archivo.
Cuando ha iniciado sesión como root, el símbolo del sistema cambia de `$` para `#`.


.. [[substep-1b]]Cambie al directorio donde se encuentran los registros de auditoría.
+
--
El directorio de registro de auditoría y los nodos aplicables dependen de la configuración del destino de auditoría.

[cols="1a,2a"]
|===
| Opción | Destino 


 a| 
Nodos locales (predeterminado)
 a| 
`/var/local/log/localaudit.log`



 a| 
Nodos de administración/nodos locales
 a| 
*** Nodos de administración (primarios y no primarios): `/var/local/audit/export/audit.log`
*** Todos los nodos: El `/var/local/log/localaudit.log` archivo normalmente está vacío o falta en este modo.




 a| 
Servidor de syslog externo
 a| 
`/var/local/log/localaudit.log`

|===
En función de la configuración de destino de auditoría, introduzca: `cd /var/local/log` O. `/var/local/audit/export/`

Para obtener más información, consulte link:../monitor/configure-audit-messages.html#select-audit-information-destinations["Seleccione destinos de información de auditoría"].

--
.. Utilice grep para extraer el link:../audit/object-ingest-transactions.html["mensajes de auditoría asociados con el objeto potencialmente perdido"] y envíelos a un archivo de salida. Introduzca: `grep uuid-valueaudit_file_name > output_file_name`
+
Por ejemplo:

+
[listing]
----
Admin: # grep 926026C4-00A4-449B-AC72-BCCA72DD1311 audit.log > /var/local/tmp/messages_about_lost_object.txt
----
.. Utilice grep para extraer los mensajes de auditoría de ubicación perdida (LLST) de este archivo de salida. Introduzca: `grep LLST output_file_name`
+
Por ejemplo:

+
[listing]
----
Admin: # grep LLST /var/local/tmp/messages_about_lost_objects.txt
----
+
Un mensaje de auditoría LLST tiene el aspecto de este mensaje de ejemplo.

+
[listing]
----
[AUDT:[NOID(UI32):12448208][CBIL(UI64):0x38186FE53E3C49A5]
[UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"][LTYP(FC32):CLDI]
[PCLD(CSTR):"/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA#3tN6"]
[TSRC(FC32):SYST][RSLT(FC32):NONE][AVER(UI32):10][ATIM(UI64):1581535134379225]
[ATYP(FC32):LLST][ANID(UI32):12448208][AMID(FC32):CLSM][ATID(UI64):7086871083190743409]]
----
.. Busque el campo PCLD y EL campo NOID en el mensaje LLST.
+
Si está presente, el valor de PCLD es la ruta completa del disco a la copia del objeto replicado que falta. El valor DE NOID es el ID de nodo de la LDR, donde se puede encontrar una copia del objeto.

+
Si encuentra una ubicación de objeto, es posible que pueda restaurar el objeto.

.. Busque el nodo de almacenamiento asociado a este ID de nodo LDR. En Grid Manager, seleccione *SUPPORT* > *Tools* > *Topología de cuadrícula*. A continuación, seleccione *_Data Center_* > *_Storage Node_* > *LDR*.
+
El identificador de nodo para el servicio LDR está en la tabla Información de Nodo. Revise la información de cada nodo de almacenamiento hasta que encuentre el que aloja esta LDR.



. Determine si el objeto existe en el nodo de almacenamiento que se indica en el mensaje de auditoría:
+
.. Inicie sesión en el nodo de grid:
+
... Introduzca el siguiente comando: `ssh admin@grid_node_IP`
... Introduzca la contraseña que aparece en `Passwords.txt` archivo.
... Introduzca el siguiente comando para cambiar a la raíz: `su -`
... Introduzca la contraseña que aparece en `Passwords.txt` archivo.
+
Cuando ha iniciado sesión como root, el símbolo del sistema cambia de `$` para `#`.



.. Determine si existe la ruta del archivo para el objeto.
+
Para la ruta de acceso del archivo del objeto, utilice el valor de PCLD del mensaje de auditoría LLST.

+
Por ejemplo, introduzca:

+
[listing]
----
ls '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'
----
+

NOTE: Escriba siempre la ruta de acceso del archivo de objetos entre comillas simples en comandos para escapar de caracteres especiales.

+
*** Si no se encuentra la ruta del objeto, el objeto se pierde y no se puede restaurar mediante este procedimiento. Póngase en contacto con el soporte técnico.
*** Si se encuentra la ruta del objeto, continúe con el paso siguiente. Puede intentar restaurar el objeto encontrado de nuevo en StorageGRID.




. Si se encontró la ruta del objeto, intente restaurar el objeto a StorageGRID:
+
.. Desde el mismo nodo de almacenamiento, cambie la propiedad del archivo de objetos para que StorageGRID lo pueda gestionar. Introduzca: `chown ldr-user:bycast 'file_path_of_object'`
.. Use SSH para iniciar sesión en cualquier nodo de almacenamiento. A continuación, acceda a la consola LDR introduciendo telnet 0 1402.
.. Introduzca: `cd /proc/STOR`
.. Introduzca: `Object_Found 'file_path_of_object'`
+
Por ejemplo, introduzca:

+
[listing]
----
Object_Found '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'
----
+
Emitir el `Object\_Found` command notifica a la cuadrícula la ubicación del objeto. También activa las políticas de ILM activas, que realizan copias adicionales según se especifica en cada política.

+

NOTE: Si el nodo de almacenamiento donde encontró el objeto está sin conexión, puede copiar el objeto en cualquier nodo de almacenamiento que esté en línea. Coloque el objeto en cualquier directorio /var/local/rangedb del nodo de almacenamiento en línea. A continuación, emita el `Object\_Found` comando que usa esa ruta de acceso al objeto.

+
*** Si el objeto no se puede restaurar, el `Object\_Found` error del comando. Póngase en contacto con el soporte técnico.
*** Si el objeto se restauró correctamente en StorageGRID, aparece un mensaje de éxito. Por ejemplo:
+
[listing]
----
ade 12448208: /proc/STOR > Object_Found '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'

ade 12448208: /proc/STOR > Object found succeeded.
First packet of file was valid. Extracted key: 38186FE53E3C49A5
Renamed '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6' to '/var/local/rangedb/1/p/17/11/00rH0%DkRt78Ila#3udu'
----
+
Continúe con el próximo paso.





. Si el objeto se restauró correctamente en StorageGRID, compruebe que se crearon nuevas ubicaciones.
+
.. Introduzca: `cd /proc/OBRP`
.. Introduzca: `ObjectByUUID UUID_value`
+
El ejemplo siguiente muestra que hay dos ubicaciones para el objeto con el UUID 926026C4-00A4-449B-AC72-BCCA72DD1311.

+
[listing]
----
ade 12448208: /proc/OBRP > ObjectByUUID 926026C4-00A4-449B-AC72-BCCA72DD1311

{
    "TYPE(Object Type)": "Data object",
    "CHND(Content handle)": "926026C4-00A4-449B-AC72-BCCA72DD1311",
    "NAME": "cats",
    "CBID": "0x38186FE53E3C49A5",
    "PHND(Parent handle, UUID)": "221CABD0-4D9D-11EA-89C3-ACBB00BB82DD",
    "PPTH(Parent path)": "source",
    "META": {
        "BASE(Protocol metadata)": {
            "PAWS(S3 protocol version)": "2",
            "ACCT(S3 account ID)": "44084621669730638018",
            "*ctp(HTTP content MIME type)": "binary/octet-stream"
        },
        "BYCB(System metadata)": {
            "CSIZ(Plaintext object size)": "5242880",
            "SHSH(Supplementary Plaintext hash)": "MD5D 0xBAC2A2617C1DFF7E959A76731E6EAF5E",
            "BSIZ(Content block size)": "5252084",
            "CVER(Content block version)": "196612",
            "CTME(Object store begin timestamp)": "2020-02-12T19:16:10.983000",
            "MTME(Object store modified timestamp)": "2020-02-12T19:16:10.983000",
            "ITME": "1581534970983000"
        },
        "CMSM": {
            "LATM(Object last access time)": "2020-02-12T19:16:10.983000"
        },
        "AWS3": {
            "LOCC": "us-east-1"
        }
    },
    "CLCO\(Locations\)": \[
        \{
            "Location Type": "CLDI\(Location online\)",
            "NOID\(Node ID\)": "12448208",
            "VOLI\(Volume ID\)": "3222345473",
            "Object File Path": "/var/local/rangedb/1/p/17/11/00rH0%DkRt78Ila\#3udu",
            "LTIM\(Location timestamp\)": "2020-02-12T19:36:17.880569"
        \},
        \{
            "Location Type": "CLDI\(Location online\)",
            "NOID\(Node ID\)": "12288733",
            "VOLI\(Volume ID\)": "3222345984",
            "Object File Path": "/var/local/rangedb/0/p/19/11/00rH0%DkRt78Rrb\#3s;L",
            "LTIM\(Location timestamp\)": "2020-02-12T19:36:17.934425"
        }
    ]
}
----
.. Cierre la sesión en la consola LDR. Introduzca: `exit`


. En un nodo de administración, busque en los registros de auditoría del mensaje de auditoría ORLM de este objeto para confirmar que la gestión del ciclo de vida de la información (ILM) ha colocado las copias según sea necesario.
+
.. Inicie sesión en el nodo de grid:
+
... Introduzca el siguiente comando: `ssh admin@grid_node_IP`
... Introduzca la contraseña que aparece en `Passwords.txt` archivo.
... Introduzca el siguiente comando para cambiar a la raíz: `su -`
... Introduzca la contraseña que aparece en `Passwords.txt` archivo.
Cuando ha iniciado sesión como root, el símbolo del sistema cambia de `$` para `#`.


.. Cambie al directorio donde se encuentran los registros de auditoría. Consulte <<substep-1b,subpaso 1. b>>.
.. Utilice grep para extraer los mensajes de auditoría asociados con el objeto en un archivo de salida. Introduzca: `grep uuid-valueaudit_file_name > output_file_name`
+
Por ejemplo:

+
[listing]
----
Admin: # grep 926026C4-00A4-449B-AC72-BCCA72DD1311 audit.log > /var/local/tmp/messages_about_restored_object.txt
----
.. Utilice grep para extraer los mensajes de auditoría Object Rules MET (ORLM) de este archivo de salida. Introduzca: `grep ORLM output_file_name`
+
Por ejemplo:

+
[listing]
----
Admin: # grep ORLM /var/local/tmp/messages_about_restored_object.txt
----
+
Un mensaje de auditoría ORLM tiene el aspecto de este mensaje de ejemplo.

+
[listing]
----
[AUDT:[CBID(UI64):0x38186FE53E3C49A5][RULE(CSTR):"Make 2 Copies"]
[STAT(FC32):DONE][CSIZ(UI64):0][UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"]
[LOCS(CSTR):"**CLDI 12828634 2148730112**, CLDI 12745543 2147552014"]
[RSLT(FC32):SUCS][AVER(UI32):10][ATYP(FC32):ORLM][ATIM(UI64):1563398230669]
[ATID(UI64):15494889725796157557][ANID(UI32):13100453][AMID(FC32):BCMS]]
----
.. Busque el campo LOCS en el mensaje de auditoría.
+
Si está presente, el valor de CLDI en LOCS es el ID de nodo y el ID de volumen donde se ha creado una copia de objeto. Este mensaje muestra que se ha aplicado el ILM y que se han creado dos copias de objetos en dos ubicaciones de la cuadrícula.



. link:resetting-lost-and-missing-object-counts.html["Restablezca el recuento de objetos perdidos o faltantes"] En Grid Manager.

